# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61c5e4b0d83ddfbeb4a6017fa3d900528bbe347d140d2be819a237887262a868cb91033fa1479b4ebbcd063b352327b894309b192d1b80213506dbbbc101d890

test:
  secret_key_base: 3bfa49ee6694b6b13436c300a71c4410f4ddab4235177cd94df0aa102e41d0819183008397c26e370eb815d82681250154765286ddba259e2171a6e3ba733eef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
